### PR TITLE
Flight Core Installation Method

### PR DESCRIPTION
**Pull request by ColonelPanicks**
This PR adds documentation and scripts to handle the installation of Underware as a tool for Flight Core.

### CODE REVIEW

**Comment by ColonelPanicks** [comment]
When using `flexec` to `bundle install` Underware I get the following error
```
Your Ruby version is 2.5.3, but your Gemfile specified 2.4.1
```

I presume the only thing that can fix this issue would be to ensure that Underware supports Ruby 2.5.3. @WilliamMcCumstie what's the likelihood of being able to have a look at this? @mjtko does this sound sane as a solution? (seeing as Flight Core isn't an rvm-like setup so installing alternate/multiple Ruby versions seems out of scope for it)

**Comment by ColonelPanicks** [comment]
The ruby versioning error mentioned above has been temporarily worked around by adding the following line to the installation script
https://github.com/alces-software/underware/blob/dev/flight-core-install/scripts/install#L62 

It's not an ideal solution but fixes it for now. This installation process has been tested and working both via the automatic and local steps.

**Comment by WilliamMcCumstie** [comment]
So I have fixed the your ruby issues but can you make a change to how the script works? Could you make a `bootstrap` script that clones the git repo and selects the branch. That way `scripts/install` installs the current branch and not `master` unless you remember to change it.

**Comment by WilliamMcCumstie** [comment]
Then you can remove the following code section as `scripts/install` always installs the locally checkout copy.
https://github.com/alces-software/underware/blob/25bf283ddfc3627544138de66f6f421704ae440b/scripts/install#L37-L47

**Comment by ColonelPanicks** [comment]
> So I have fixed the your ruby issues but can you make a change to how the script works? Could you make a `bootstrap` script that clones the git repo and selects the branch. That way `scripts/install` installs the current branch and not `master` unless you remember to change it.

By default the script installs `alces_VERSION` branch (which at the moment is set to `0.6.0-rc1`) and not the `master` branch.

> Then you can remove the following code section as `scripts/install` always installs the locally checkout copy. Possible remove some variables as well.
> [underware/scripts/install](https://github.com/alces-software/underware/blob/25bf283ddfc3627544138de66f6f421704ae440b/scripts/install#L37-L47)
> 
> Lines 37 to 47 in [25bf283](/alces-software/underware/commit/25bf283ddfc3627544138de66f6f421704ae440b)

From discussion IRL we've settled on changing the default behaviour of `scripts/install` such that local installation will not checkout different branches unless explicitly stated.

**Pull request merged**
